server:
  port: 8080  # 8080번 포트로 애플리케이션 실행
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bulletinboard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul # 데이터베이스 이름 bulletinboard
    username: root  # mysql username로 변경
    password: qkr112255!!  # mysql password로 변경
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  # create: 정의된 엔티티 데이터베이스 추가, update: 변경점만 반영, create-drop: 데이터베이스 반영 후 애플리케이션 종료 시 삭제, validate: 동일 여부 확인, none: 아무것도 하지 않음
    open-in-view: true # View layer 에서 JPA 영속성 관련 세션 연결을 허용하지 않는다 => false, 허용한다 => true
    generate-ddl: true  # DDL 생성
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true